services:
  django:
    build: .
    platform: linux/arm64
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - dynamodb
      - s3

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"

  s3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9000:9000"
    command: server /data
